name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'inte/**'
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    environment: production
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'# Specify the Node.js version you need

      - name: Install dependencies
        run: |
          cd apps/web
          npm install
          npm install -g typescript # Install TypeScript globally

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_build_command: 'npm run build-prod'
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_GROUND_0B1871503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./apps/web" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
