name: Build and deploy Node.js app to Azure Web App - mia15api

on:
  push:
    branches:
      - main
    tags:
      - 'inte/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies with npm
        run: |
          cd apps/api
          npm install --no-frozen-lockfile
          npm run build

      - name: Zip artifact for deployment
        run: |
          cd apps/api
          zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: apps/api/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_68FFA76D9EE3470EA4E66E67FAD3AF33 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ADD151ECB26D42A4A16C63BFFCA03897 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_01A28C744DB94B7DA53ABF33CBB51DDD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'mia15api'
          slot-name: 'Production'
          package: .